# Generated by Django 4.2.16 on 2025-08-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_userprofile_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.CharField(blank=True, help_text='关联的学生证号码', max_length=50, null=True, verbose_name='学生证号码'),
        ),
    ]
