# Generated by Django 4.2.16 on 2025-07-13 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("jcourse_api", "0043_alter_reviewrevision_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_content",
                    models.TextField(
                        help_text="学生对教师的评价内容", verbose_name="评价内容"
                    ),
                ),
                (
                    "data_sources",
                    models.CharField(
                        help_text="数据来源标识，如data-1,data-2",
                        max_length=100,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "evaluation_count",
                    models.IntegerField(
                        default=1, help_text="该教师的评价条数", verbose_name="评价条数"
                    ),
                ),
                (
                    "source_data",
                    models.CharField(
                        db_index=True,
                        help_text="用于去重的原始数据标识",
                        max_length=255,
                        verbose_name="原始数据标识",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="jcourse_api.teacher",
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师评价",
                "verbose_name_plural": "教师评价",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="teacherevaluation",
            constraint=models.UniqueConstraint(
                fields=("teacher", "source_data"), name="unique_teacher_evaluation"
            ),
        ),
    ]
