# Generated by Django 4.2.16 on 2025-08-08 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0044_teacherevaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名/昵称')),
                ('contribution_type', models.CharField(choices=[('code', '代码贡献'), ('design', '设计贡献'), ('translation', '翻译贡献'), ('documentation', '文档贡献'), ('testing', '测试贡献'), ('feedback', '反馈建议'), ('other', '其他贡献')], default='code', max_length=50, verbose_name='贡献类型')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='贡献描述')),
                ('avatar', models.URLField(blank=True, verbose_name='头像链接')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub用户名')),
                ('contributions', models.PositiveIntegerField(default=1, verbose_name='贡献次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '贡献者',
                'verbose_name_plural': '贡献者',
                'ordering': ['-contributions', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('role', models.CharField(max_length=100, verbose_name='职位')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='简介')),
                ('avatar', models.URLField(blank=True, verbose_name='头像链接')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub用户名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '团队成员',
                'verbose_name_plural': '团队成员',
                'ordering': ['order', 'name'],
            },
        ),
    ]
