# Generated by Django 4.2.16 on 2025-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0045_contributor_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='class_name',
            field=models.CharField(blank=True, help_text='如：2021级金融学1班', max_length=100, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='class_name',
            field=models.CharField(blank=True, help_text='如：2021级金融学1班', max_length=100, verbose_name='班级'),
        ),
    ]
