# Generated by Django 4.2.16 on 2025-08-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0046_contributor_class_name_teammember_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='qq',
            field=models.CharField(blank=True, max_length=20, verbose_name='QQ号'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='wechat',
            field=models.CharField(blank=True, max_length=100, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='team_avatars/', verbose_name='头像'),
        ),
    ]
