# Generated by Django 4.2.16 on 2025-09-04 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0047_teammember_qq_teammember_wechat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now, verbose_name='访问日期')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='国家')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='地区/省份')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='城市')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '访问统计',
                'verbose_name_plural': '访问统计',
                'ordering': ['-created_at'],
                'unique_together': {('visit_date', 'ip_address')},
            },
        ),
    ]
